package com.orangomango.snake;

public enum PlayAchievement{
	MANGOEATER_1("CgkI0ZmR74UBEAIQBg"),
	MANGOEATER_2("CgkI0ZmR74UBEAIQBw"),
	MANGOEATER_3("CgkI0ZmR74UBEAIQCA"),
	MANGOEATER_4("CgkI0ZmR74UBEAIQCQ"),
	MANGOEATER_5("CgkI0ZmR74UBEAIQCg"),

	EASY_1("CgkI0ZmR74UBEAIQGg"),
	EASY_2("CgkI0ZmR74UBEAIQFA"),
	EASY_3("CgkI0ZmR74UBEAIQFw"),

	MEDIUM_1("CgkI0ZmR74UBEAIQIQ"),
	MEDIUM_2("CgkI0ZmR74UBEAIQFQ"),
	MEDIUM_3("CgkI0ZmR74UBEAIQGQ"),

	HARD_1("CgkI0ZmR74UBEAIQEQ"),
	HARD_2("CgkI0ZmR74UBEAIQEw"),
	HARD_3("CgkI0ZmR74UBEAIQDw"),

	EXTREME_1("CgkI0ZmR74UBEAIQHA"),
	EXTREME_2("CgkI0ZmR74UBEAIQFg"),
	EXTREME_3("CgkI0ZmR74UBEAIQHw"),

	FRIENDS_1("CgkI0ZmR74UBEAIQIg"),
	FRIENDS_2("CgkI0ZmR74UBEAIQGw"),

	WORLD_EATER("CgkI0ZmR74UBEAIQIA"),
	CHAMALEON("CgkI0ZmR74UBEAIQEA"),
	CONNECTED("CgkI0ZmR74UBEAIQEg"),

	GAMEOVER_1("CgkI0ZmR74UBEAIQHg"),
	GAMEOVER_2("CgkI0ZmR74UBEAIQHQ"),
	GAMEOVER_3("CgkI0ZmR74UBEAIQGA");

	private String id;

	private PlayAchievement(String id){
		this.id = id;
	}

	public String getId(){
		return this.id;
	}
}
